const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 130,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 180,
      brand: "Lacoste",
      rating: "4.0",
      numReviews: 18,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 180,
      brand: "Adidas",
      rating: "4.0",
      numReviews: 28,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 80,
      brand: "Puma",
      rating: "4.5",
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 160,
      brand: "Nike",
      rating: "4.0",
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 90,
      brand: "Adidas",
      rating: "4.0",
      numReviews: 16,
      description: "high quality product",
    },
  ],
};

export default data;
